#!/bin/sh

# Empty all rules
sudo iptables -t filter -F
sudo iptables -t filter -X

# Bloc everything by default
sudo iptables -t filter -P INPUT DROP
sudo iptables -t filter -P FORWARD DROP
sudo iptables -t filter -P OUTPUT DROP

# Authorize already established connexions
sudo iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
sudo iptables -t filter -A INPUT -i lo -j ACCEPT
sudo iptables -t filter -A OUTPUT -o lo -j ACCEPT

# ICMP (Ping)
sudo iptables -t filter -A INPUT -p icmp -j ACCEPT
sudo iptables -t filter -A OUTPUT -p icmp -j ACCEPT

# SSH
sudo iptables -t filter -A INPUT -p tcp --dport 22 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 22 -j ACCEPT

# DNS
sudo iptables -t filter -A OUTPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p udp --dport 53 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 53 -j ACCEPT
sudo iptables -t filter -A INPUT -p udp --dport 53 -j ACCEPT

# HTTP
sudo iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT

#HTTPS
sudo iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT

# FTP
sudo iptables -t filter -A OUTPUT -p tcp --dport 20:21 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 20:21 -j ACCEPT

# Git
sudo iptables -t filter -A OUTPUT -p tcp --dport 9418 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 9418 -j ACCEPT

# Mail SMTP
iptables -t filter -A INPUT -p tcp --dport 25 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 25 -j ACCEPT

# Mail POP3
iptables -t filter -A INPUT -p tcp --dport 110 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 110 -j ACCEPT

# Mail IMAP
iptables -t filter -A INPUT -p tcp --dport 143 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 143 -j ACCEPT

# NTP (server time)
sudo iptables -t filter -A OUTPUT -p udp --dport 123 -j ACCEPT

#NAT – Internet
sudo iptables –t nat –A POSTROUTING –s 192.168.5.0/24 –o ens18 –j SNAT --to-source 10.100.0.61

#NAT – Web
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 80 -j DNAT --to-destination 192.168.5.32
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 443 -j DNAT --to-destination 192.168.5.32

#NAT - Mail
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 25 -j DNAT --to-destination 192.168.5.128
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 143 -j DNAT --to-destination 192.168.5.128
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 110 -j DNAT --to-destination 192.168.5.128

#NAT – FTP (WebServer)
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 20:21 -j DNAT --to-destination 192.168.5.32
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 20:21 -j DNAT --to-destination 192.168.5.32

#NAT – DNS
sudo iptables -t nat -A PREROUTING -p tcp -i ens18 --dport 53 -j DNAT --todestination 192.168.5.64
sudo iptables -t nat -A PREROUTING -p udp -i ens18 --dport 53 -j DNAT --todestination 192.168.5.64 


